### ISSUE TITLE
Recent update of sunspot (2.2.0) is breaking some `have_search_params`

### ISSUE THREAD

**Issue by bjegannathan-rpx** [pivotal/sunspot_matchers#21]
I upgraded to the latest sunspot Gem to `2.2.0` which was released on April 9 2015. Some of the specs that use to run are now breaking with an error like below

```
  1) SampleClass#sample_method should do solr query to do something
     Failure/Error: Sunspot.session.should have_search_params(:with, :is_open, true)
       expected search params: fq => ["type:RandomClass", "random_id:123", "{!tag=sd2f8dtkyg5z}is_open_bs:true"] to match expected: fq => ["is_open_bs:true"]
     # ./spec/models/***_spec.rb:36:in `block (3 levels) in <top (required)>'
```

My Spec file
```
    SampleClass.sample_method(params)
    Sunspot.session.should have_search_params(:with, :is_open, true)
```

If you notice there is an extra `{!tag=sd2f8dtkyg5z}` getting appended to the with option. This is fine as far as interacting with Solr server as it is something that is used behind the scenes. However, from the `sunspot_matchers` perspective, can you make it ignore and perhaps still have the old test work ? Let me know if you need any more detail on this.

Note: I have renamed my class name and method name for obvious reasons to SampleThis SampleThat.

**Comment by jpalermo** [comment]
Hmm, I don't see any major differences in the tagging behavior in Sunspot 2.2.

Normally Sunspot only adds a tag to a field query when that field is used in a facet. Have you recently added faceting to your search method?

**Comment by bjegannathan-rpx** [comment]
@jpalermo : Yes, I do have facets. However, I did not add them after or before the upgrade, it has always been there.

**Comment by jpalermo** [comment]
And what version of sunspot_matchers are you using/were you using?

**Comment by bjegannathan-rpx** [comment]
I was using `sunspot_matchers (1.3.0.2)`. I am using the latest one now `sunspot_matchers (2.1.1.2)`

**Comment by jpalermo** [comment]
Previously the matcher was converting the expected value into a regex and looking anywhere in the actual search for that regex. This caused problems with `without` matchers since the difference between a `with` and `without` in terms of the generated search is simply a `-` sign in front of the term.

This was fixed by anchoring the regex to the start of the string with a `^`.

One way you can work around this is by doing a facet on the column in your test using the block syntax. I'd say this is a less than ideal solution though.

Thinking about it again, it seems to work if I change the regex to have a non-capturing negative look behind of the `-` sign. I think this will prevent the problems from #14 but allow matching even when there is a tag.

I'll look for more edge cases that this breaks and hopefully get a new version in the next day or so if I can't find any.

**Comment by jpalermo** [comment]
I think the changes I made in 2.2.0.0 should work.

**Comment by bjegannathan-rpx** [comment]
Thank you very much for the patch. The new tag `2.2.0.0` did fix some of the issues. However the ones surrounding facets are still failing. Apologies for not mentioning them before.

The spec
```
Sunspot.session.should have_search_params(:facet) {
  active_condition = with(:is_open, 'true')
  facet(:is_open, :exclude => active_condition)
}
```

Failure
```
Failure/Error: Sunspot.session.should have_search_params(:facet) {
  expected search params: f.is_open_bs.facet.mincount =>  and facet.field =>  to match expected: f.is_open_bs.facet.mincount => [1] and facet.field => ["{!ex=kdpn7fc02gub}is_open_bs"]
```

Let me know if you need any other inputs from me.

**Comment by jpalermo** [comment]
In this case, that error is showing that the actual search that was performed doesn't seem to have the same facets declared on it as the expectation. That seems correct to me.

I'm guessing that you would have expected facets to exist. Maybe put some debugging wherever your search is being generated to find out why facets aren't being declared.
